// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestDiplom.Areas.AdminPanel.Data;

#nullable disable

namespace TestDiplom.Migrations.ShopCartiMigrations
{
    [DbContext(typeof(ShopCarti))]
    [Migration("20230613171814_yht")]
    partial class yht
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TestDiplom.Areas.AdminPanel.Models.CartLine", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("Year_creating")
                        .HasColumnType("bigint");

                    b.Property<int>("Year_public")
                        .HasColumnType("int");

                    b.Property<long>("cost_bo")
                        .HasColumnType("bigint");

                    b.Property<string>("guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title_bok")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("lines");
                });

            modelBuilder.Entity("TestDiplom.Areas.AdminPanel.Models.Courier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("KolvoZakaz")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("familya")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imya")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("otchestvo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("cour");
                });

            modelBuilder.Entity("TestDiplom.Areas.AdminPanel.Models.Order", b =>
                {
                    b.Property<long>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("order_id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("t1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("tir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("order_id");

                    b.HasIndex("t1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TestDiplom.Areas.AdminPanel.Models.Order", b =>
                {
                    b.HasOne("TestDiplom.Areas.AdminPanel.Models.Courier", "cour")
                        .WithMany("Заказы")
                        .HasForeignKey("t1");

                    b.Navigation("cour");
                });

            modelBuilder.Entity("TestDiplom.Areas.AdminPanel.Models.Courier", b =>
                {
                    b.Navigation("Заказы");
                });
#pragma warning restore 612, 618
        }
    }
}
